### ISSUE TITLE
Setup Guides for OpenCost

### ISSUE THREAD

**Issue by davidcollom** [jetstack/finops-stack#1]
OpenCost's installation is not as straightforward as one would expect, there are API Keys for basic functions along with ServiceAccount keys for more in-depth

## Acceptance
- Get OpenCost up and running with details displaying within UI
- OpenCost should use Google Managed Prometheus within GCP
- Have some pages with easy-to-follow docs
- Must cover GCP as primary but other providers should be possible
  - If not possible, we can use some of OpenCosts - but with our own recommendations (WorkloadID etc)

## Notes

OpenCost docs can be found under: https://www.opencost.io/docs/configuration/on-prem

For GCP - I'd love for us to try and get WorkloadID working OVER service account keys 🙏  but that's a stretch goal at this stage

**Comment by cyberbliss** [comment]
I'm closing this one as we are using Prometheus Opencost Exporter rather than Opencost; the difference is that the Exporter only exposes the metrics (for scraping), whereas Opencost also includes a web UI (which we don't need because we are using Grafana)
